language: objective-c
osx_image: xcode8
before_install:
  - cd iOS_SDK
script:
  - xcodebuild -list
  - xcodebuild build -scheme OneSignal-Dynamic
  - xcodebuild -scheme UnitTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' test