language: objective-c
osx_image: xcode9
before_install:
  - cd iOS_SDK/OneSignalSDK
script:
  - xcodebuild -list
  - xcodebuild -scheme UnitTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.0' test
