# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ hack-cicd ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: iOS_SDK/OneSignalDevApp/OneSignalExample.xcodeproj
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: iOS_SDK/OneSignalSDK.xcworkspace # optional

    distribute:
      runs-on: ubuntu-latest
      steps:
        - name: Setup NPM
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install App Center CLI
          run: npm install -g appcenter-cli

        - name: Upload IPA
          run: echo todo